### ISSUE TITLE
In TS, using the default values in example have type conflict

### ISSUE THREAD

**Issue by haoyangL-lf** [ndom91/react-timezone-select#101]
### Describe the bug

In Typescript, when I try to get the default values as suggested in the example:

```
const [selectedTimezone, setSelectedTimezone] =useState(
    Intl.DateTimeFormat().resolvedOptions().timeZone
  )
```

When adding the component as the usage example shows:

```
<TimezoneSelect
          value={selectedTimezone}
          onChange={setSelectedTimezone}
        />
```

This will give type conflict error on the `onChange` function:

```
Type 'Dispatch<SetStateAction<string>>' is not assignable to type '(timezone: ITimezoneOption) => void'.
  Types of parameters 'value' and 'timezone' are incompatible.
    Type 'ITimezoneOption' is not assignable to type 'SetStateAction<string>'
```

This is because `Intl.DateTimeFormat().resolvedOptions().timeZone` is a string value and the onChange requires the `ITimezoneOption` object.

How do I address this problem?

### Reproduction

use the usage example in Typescript.

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.56 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 15.6.1
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Thanks for bringing this to my attention, it should also take a `string` actually. Let me take a closer look at what happened there 🙏

**Comment by GJmelody** [comment]
having the same issue

**Comment by kylebesser** [comment]
Any update on this? Same issue here.

**Comment by tmountain** [comment]
Same issue for me.

**Comment by tmountain** [comment]
Hacky solution:

```
import TimezoneSelect, { ITimezoneOption } from "react-timezone-select";

const [selectedTimezone, setSelectedTimezone] = useState(
    Intl.DateTimeFormat().resolvedOptions().timeZone
);
 
const handleTimezoneChange = (timezoneOption: ITimezoneOption) => {
    setSelectedTimezone(timezoneOption.value);
};

<TimezoneSelect value={selectedTimezone} onChange={handleTimezoneChange} />
```

**Comment by kylebesser** [comment]
@tmountain I am getting an undefined is not a function error on line 207 of the index.js file. Did you see this issue also?

**Comment by ndom91** [comment]
Hey sorry yall that this has taken so long, I've widen the allowed type allowed to be used as the `onChange` argument in `2.1.4` (just published to npm). Can you give it a shot and let me know if it fixes it for you? Thanks!

**Comment by kirbysayshi** [comment]
I believe this is still an issue. The types of `onChange` in the `Props` is tied to the same generic as the initial `value`, meaning if you pass an initial string, the `onChange` type becomes a string. But after testing it seems it always returns in `ITimezoneOption`.

https://github.com/ndom91/react-timezone-select/blob/d5fb619edbad7feee01600e5ba740f160f285ad9/src/types/timezone.ts#L30-L31

Changing `onChange` to accept `ITimezoneOption` instead of `ITimezone` will fix the issue, I believe.

**Comment by ndom91** [comment]
@kirbysayshi hmm so the `ITimezone` should accept `ITimezoneOption` as well as `string`. See:

```ts
export type ITimezoneOption = {
  value: string
  label: string
  abbrev?: string
  altName?: string
  offset?: number
}

export type ITimezone = ITimezoneOption | string
```

**Comment by kirbysayshi** [comment]
@ndom91 Right! But that's not the issue. I was wrong in my initial report, and I apologize for any confusion. The issue is not due to the generics. It's due to `onChange`'s argument being typed as `ITimezone`, when it's actually always an `ITimezoneOption`. [Here's a TSPlayground that demonstrates the issue.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxJwC+cAZlBCHAERSoYsDcAUKJLEQcYAEQDyAWXqNmbYQFoAJk259w0eABVQSAF4QAdqSQAbJBmw4ecODACeYKgEltIPYaSZrth89fujMTAYYEMvGyIkf30jElNzLG8UExNoj0IvWgYmVnZ0GHkQtxikeWIzTl4eJAAPAXg6fAMMUIM4AGFwAAoASlxvNENCeDwwFChiNKMaOABeAkmdEriKmC68IoCkQgAuOGTUpfSaHqqbAHpz2104YEJ9tpcjwODWgaH4AG0YXWxiGE0ugAunMFqRyJQur05gA+bw2MYTKLPJBdJwGGAmAB0IgoyLcADFoCAKL0sexCBATAA3JCKIIhIZkzYALQ8PXCcFOPG87Bg+CgbS68LgAB4psZViKLlcnsUPAy3jZlXBqcl8EhZjgftRpXBDO0ABYoAwAc01OC6SGpfVmMP6KpVlzgmkNd1u9xNcCQUEYUDgACNzChInAAAbWsMel0kHyOcNyrZhrFwAByEEotmN8GAOcIeplcETJTg7FN40UZkI9wgdCzVGABjA+HgYbVJg1UfsjixBbg-0BVptZ0dhfTmZg2fr+ww+GSpaam37xvjtfDkejAH1kgB3FB2QibhMSxWGZN9wYGSlmLEmCCmoenODOvDtjV7ADkWO-H+wJhQQYmJ+35Yh+NA8qONjAHWXTdkga7WnAACEszzCwwxQI2posH0ViQcqzrpjucA7kgH7sPqADWgbBqGmixsa9wGOMjCkYofY2AOuiPrw+G6qO1D8QRcI2NyurVHUGj0E0LSGB04AABJMEgAAKKDmiISAgBAABCjCUUgBjQnhcCXsMuBwIiizytMtDzJEEorAk6y2Ciuz7CkEr3NQ3LeM6PzRig-YwJhZoge8V5fD8fxIACwKgpEZB4sKKrQnaRYYtiuKUP4RJQCSaw9OS2xUrS9KvEyRWsh4nK+TYfICkKIriiiTkYHqzoYVhepvhaOp6gaxpmhaj6wg6kHOq67rul6Pp+jRaAhsQ67UlG7r0XGVBhsWHjnvhXE8RBkHQXAsG+Ah1LIahrBdWaOHjfhzpkMAKRwAYGZUQtS1UMMeLenUCSesFoWmuF+GcbFg7WnV4POsatK2BAcCmlAAHTmA-6NsDWGquqDaRag7Hg-2kPcdaWK9dyfF6oJIrnCJXK8LqQA)

In my opinion, I think the signature for onChange should be changed to more accurately reflect how it behaves:

```diff
-  onChange?: (timezone: ITimezone) => void 
+ onChange?: (timezone: ITimezoneOption) => void 
```

`onChange` always returns a parsed timezone object, right?

**Comment by kirbysayshi** [comment]
Yeah that makes sense. I think there are two issues then:

1) type is wrong on the `onChange` callback, it's always `ITimezoneOption`
2) the examples are wrong, since they imply that a string is possible within the `onChange` callback (via the `useState` generic, which is what this issue is originally about)

**Comment by ndom91** [comment]
@kirbysayshi okay I've updated the `onChange` type, but regarding the examples, I think that's still okay, no?

Lets take this one from the README.md as an example:

```ts
const [selectedTimezone, setSelectedTimezone] = useState<ITimezone>('Europe/Berlin')

<TimezoneSelect
  value={selectedTimezone}
  onChange={setSelectedTimezone}
/>
```

So `value` is initially a string, the timezone is looked up and matched internally, etc. and a full `ITimezoneOption` object is generated.

This is then used as the argument to the `onChange` handler, which in this example is the setter from the `useState`. So then in effect `selectedTimezone` becomes the the full `ITimzoneOption` object as well. 

That's how I envisioned it working, so then you have the full timezone object to read values off of, etc. in yuor applicaiton in `selectedTimezone`.

**Comment by kirbysayshi** [comment]
@ndom91 My apologies for the delay! #120 looks great!

The example does make sense. I think because the types for onChange were wrong, our code probably had `useState<ITimezoneOption>('Europe/Berlin')`, and that caused me to be confused.

Thanks for understanding as I worked through this!
