### ISSUE TITLE
Automatic browser detection

### ISSUE THREAD

**Issue by VictorBaudot** [ndom91/react-timezone-select#3]
How would you guess user timezone to put it as default value?

**Comment by VictorBaudot** [comment]
```js
const moment = require("moment-timezone");
moment.tz.guess();
```

**Comment by alfonmga** [comment]
Moment.js uses `Intl.DateTimeFormat().resolvedOptions().timeZone` under the hood, but the problem is that returned value doesn't match `react-timezone-select` values.

For example, running that API I get `Europe/Madrid` but `react-timezone-select` expects value to be [`Europe/Brussels`](https://github.com/ndom91/react-timezone-select/blob/8dc270bdc58fac0cb0c3ced4ce782f71bb5489c8/src/index.js#L33).

Do you guys know how I can get the _correct_ timezone?

@ndom91

**Comment by ndom91** [comment]
@alfonmga hmm very good question - the problem is we start with an array of predefined key value pairs i.e.

```
const i18n = {
  'Pacific/Midway': 'Midway Island, Samoa',
  'Pacific/Honolulu': 'Hawaii',
  'America/Juneau': 'Alaska',
  'America/Dawson': 'Tijuana, Pacific Time',
  'America/Boise': 'Mountain Time',
  'America/Chihuahua': 'Chihuahua, La Paz, Mazatlan',
```

And anything not in there isn't recognized unfortunately. Let me see if I can get the library itself to convert between other ways of writing the timezone and what it expects. For example, 'Europe/Berlin' or 'Europe/Madrid' = 'Europe/Brussels'
