### ISSUE TITLE
How to get the initial data

### ISSUE THREAD

**Issue by chandru-altrosyn-dev** [ndom91/react-timezone-select#31]
Hi,

  I'm getting the below object onChange event.

```
  {
   value: 'America/Juneau'
   label: '(GMT-8:00) Alaska,
   abbrev: 'AHST',
   offset: -8,
   altName: 'Alaskan Standard Time'
 }
```
 In my case, I load the form with some predefined data and pass the initial timezone value

```
const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);

// assume we have some other fields here
<TimezoneSelect
      value={timezone}
      onChange={setTimezone}
      menuPosition="absolute"
      menuPlacement="auto"
/>
// assume that we have a submit button here
```

So, on rendering the form the timezone is preselected with my local timezone. But I didn't get the offset object in timeZone useState, I'm getting those data onChange the TimezoneSelect(react-select). 

How to get the initial data with offset without changing the dropdown?

or How to trigger the onChange event?

In your official sample itself, we have that issue. In the code section, it displays _"Europe/Rome"_ without showing the actual object, it only displays on selecting the same value again. 

Is that possible to show the selected object value in onLoading?

![image](https://user-images.githubusercontent.com/68065664/119458289-35aa6d80-bd5a-11eb-9517-7aa3c139bb38.png)

Thanks,
Chandru

**Comment by ndom91** [comment]
Hi Chandru,

Thanks for pointing this out! You're right the initial set does not get a return object with all the details nicely filled out as no events have fired yet.

This must happen kind of outside of the responsibility of this `react-timezone-select` component. Are you using any date/time library like `moment` or `spacetime`? If so, we can see if they have any helper functions for getting timezone offsets.

Otherwise, it seems the standard javascript `Date()` has a function which can help us.

You can get the current users offset like so:

```js
const now = new Date()
const timezoneOffsetMinutes = now.getTimezoneOffset()    // -120 for GMT-2:00, for example
const offsetHours = timezoneOffsetMinutes / 60           // -2
```

Does that help with what you're trying to do?

**Comment by chandru-altrosyn-dev** [comment]
@ndom91 Thanks for your response.

Yeah, that helps. I thought that we have some solution to get the initial obj through react-timezone-select. 

```
  const now = new Date();
  const timezoneOffsetMinutes = now.getTimezoneOffset(); // -120 for GMT-2:00, for example
  const offsetHours = timezoneOffsetMinutes / 60;

  const [timezone, setTimezone] = useState({
    value: Intl.DateTimeFormat().resolvedOptions().timeZone,
    offset: offsetHours
  });

  <TimezoneSelect
    value={**timezone.value**}
    onChange={setTimezone}
    menuPosition="absolute"
    menuPlacement="auto"
  />
```

The above code works fine.
