### ISSUE TITLE
Optional offset field

### ISSUE THREAD

**Issue by emagaram** [ndom91/react-timezone-select#67]
This might be a basic question but for the ITimezoneOption type, Typescript says the offset field is optional but for all the select options I clicked on, the offset field was there. Is this a mistake? How can I ensure that all select option fields have an offset?

**Comment by ndom91** [comment]
All auto-generated timezones will have an offset, yes. 

Its only potentially an issue with custom timezone additions. Although we try to match those up with existing offsets as well as best as possible.

Can you maybe provide a specific use-case where you're worried an offset might be missing? Or are you just asking because the typescript type was optional?

**Comment by ndom91** [comment]
@emagaram sorry this took so long, but I've released `1.3.2` just now, and tightened up the types a bit. `offset` is no longer optional, as it is required to be there in each timezone entry :+1:
